---
driver:
  name: ec2
  require_chef_omnibus: true
  instance_type: m4.large
  region: us-east-1
  aws_ssh_key_id: <%= ENV['TOPHAT_EC2_KEY'] %>
  security_group_ids: <%= ENV['TOPHAT_SG'] %>
  subnet_id: <%= ENV['TOPHAT_SUBNET_ID'] %>
  tags:
    Name: jenkins-test-kitchen
    owner: <%= ENV['USER'] %>
  associate_public_ip: true

provisioner:
  name: chef_solo
  cookbooks_path:
    - ./cookbooks

platforms:
  - name: amznlnx-ec2
    driver:
      image_id: ami-60b6c60a
    transport:
      username: ec2-user
  - name: ubuntu-14.04-ec2
    driver:
      image_id: ami-7e055c14
    transport:
      username: ubuntu
  - name: ubuntu-14.04-local
    driver:
      name: vagrant
      box: opscode-ubuntu-14.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
  - name: centos-7.1-ec2
    driver:
      image_id: ami-61bbf104
    transport:
      username: centos
  - name: centos-7.1-local
    driver:
      name: vagrant
      box: opscode-centos-7.1
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[jenkins-config::default]
    attributes:
